---
- name: Show Version
  hosts: all
  gather_facts: false
  connection: local

  tasks:
   - name: Show Version
     ios_command:
       commands:
         - show version
         - show ip int br
         - show ip route summ

     register: output

   - name: Display output
     debug: var=output.stdout_lines

##Added Test String --Deven
##Test Branch --Deven
##Test Branch2 --Deven
#Help

#I'm trying!!
#Testing
#One
#TestNOW!!